// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jogdbjuwziwhvhevnhsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZ2RianV3eml3aHZoZXZuaHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2MzE0OTcsImV4cCI6MjA0OTIwNzQ5N30.3gY_6cWnVXHsT80REJt3Yq_KD8JSGdqw767A0SXGifI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);